/**
 * %class%
 *
 * Class automatically generated by dcReferenceModelPlugin
 * on %date%.
 */
class Base%class% implements dcReferenceClassInterface
{
  const
    %constants%
  ;

  /**
   * Get the identifiers for %class% reference class.
   *
   * @return array int[]
   */
  public static function getIdentifiers()
  {
    return array(
      %identifiers%
    );
  }

  /**
   * Get the options for %class% reference class.
   *
   * @return array
   */
  public static function getOptions()
  {
    return array(
      %options%
    );
  }

  /**
   * Get the string representation of the option identified by $identifier
   * for %class% reference class, or null if it's not a valid identifier.
   *
   * @return string or null
   */
  public static function toString($identifier)
  {
    $options = self::getOptions();

    if (array_key_exists($identifier, $options))
    {
      return $options[$identifier];
    }
  }

}